### ISSUE TITLE
Colour contrast of labels and general accessibility

### ISSUE THREAD

**Issue by johnpauldickie** [alphagov/govuk-display-screen#11]
It's been pointed out that the contrast on the labels used on the display screen are quite poor.

These such as:
```
  <h1>Live searches on GOV.UK:</h1>
  <h1>Trending content from last 7 days traffic on GOV.UK:</h1>
  <h1>Recent content from departments:</h1>
```
`.content li em`, `.searches h1` should be changed to improve contrast (maybe using [design system colours](https://design-system.service.gov.uk/styles/colour/)?)

What else could be improved to bring the display screen more inline with the design system and more accessible?

**Comment by stevenjmesser** [comment]
Thanks for this, JP, it's a great suggestion.
